// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonsterLog.Models;

namespace MonsterLog.Migrations
{
    [DbContext(typeof(MonsterDBContext))]
    partial class MonsterDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MonsterLog.Models.Monster", b =>
                {
                    b.Property<int>("MonsterID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Diet");

                    b.Property<string>("Habitat");

                    b.Property<string>("Image");

                    b.Property<string>("LifeSpan");

                    b.Property<string>("Lore");

                    b.Property<string>("Name");

                    b.Property<string>("NaturalStrengths");

                    b.Property<string>("NaturalWeakness");

                    b.Property<string>("Size");

                    b.HasKey("MonsterID");

                    b.ToTable("Monsters");
                });
#pragma warning restore 612, 618
        }
    }
}
